filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '${LOGFILE_PATH:/var/log/app}/graphql.log'
setup.kibana:
  host: '${KIBANA_HOST}'

output.logstash:
  hosts: ['${LOGSTASH_HOST}']
  pipelining: 0
